global:
  vanityURL: "jum-api-e27db1-prod.apps.gold.devops.gov.bc.ca"
  commit_sha: ""
  image:
    tag: telemetry
  environment: prod
  licenseplate: e27db1

notification:
  image:
    repository: jum-notification
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "telemetry"

backend:
  justinSecured: true
  route:
    enabled: true