global:
  vanityURL: "jum-api-e27db1-test.apps.gold.devops.gov.bc.ca"
  commit_sha: ""
  image:
    tag: develop
  environment: test
  licenseplate: e27db1

notification:
  image:
    repository: jum-notification
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "develop"

backend:
  justinSecured: true
  route:
    enabled: true