{{ $release := .Release.Name }}
{{ $ocEnv := regexFind "([^-]*$)" .Release.Namespace }}
{{ $domain := .Values.global.vanityURL }}
{{ $isPR := hasPrefix "pr-" .Release.Name }}
## Derived release name
{{ $drn := ternary $release $ocEnv $isPR }}
{{ $isProd := contains "prod" $ocEnv }}
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notification.fullname" . }}
  labels:
    {{- include "notification.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "notification.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.global.commit_sha }}
        commit_sha: {{ .Values.global.commit_sha }}
        {{- end}}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "notification.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.global.licenseplate }}-vault
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KafkaCluster__SslCaLocation
              value: /opt/kafka/certificates/server-ca.crt
            - name: KafkaCluster__SslCertificateLocation
              value: /opt/kafka/certificates/client-ca.crt
            - name: KafkaCluster__SslKeyLocation
              value: /opt/kafka/certificates/client.key
            - name: KafkaCluster__SaslOauthbearerTokenEndpointUrl
              valueFrom:
                secretKeyRef:
                  name: jum-kafka-config-notification
                  key: KafkaCluster__SaslOauthbearerTokenEndpointUrl
            - name: KafkaCluster__SaslOauthbearerProducerClientId
              valueFrom:
                secretKeyRef:
                  name: jum-kafka-config-notification
                  key: KafkaCluster__ProducerClientId
            - name: KafkaCluster__SaslOauthbearerConsumerClientId
              valueFrom:
                secretKeyRef:
                  name: jum-kafka-config-notification
                  key: KafkaCluster__ConsumerClientId
            - name: KafkaCluster__BootstrapServers
              valueFrom:
                secretKeyRef:
                  name: jum-kafka-config-notification
                  key: KafkaCluster__BootstrapServers
            - name: KafkaCluster__TopicName
              valueFrom:
                secretKeyRef:
                  name: jum-kafka-config-notification
                  key: KafkaCluster__TopicName
            - name: KafkaCluster__AckTopicName
              valueFrom:
                secretKeyRef:
                  name: jum-kafka-config-notification
                  key: KafkaCluster__AckTopicName
            - name: KafkaCluster__NotificationTopic
              valueFrom:
                secretKeyRef:
                  name: jum-kafka-config-notification
                  key: KafkaCluster__NotificationTopic
            - name: DB_HOST
              value: jum-database
            - name: SA_PASSWORD
              value:
            - name: SA_USER
              value: admin
            - name: DATABASE
              value: JumDB
            - name: ConnectionStrings__JumDatabase
              valueFrom:
                configMapKeyRef:
                  name: jum-api-database
                  key: CONNECTION_STRINGS_JUM
            - name: ApplicationUrl
              value: "https://{{ if $isProd }}{{else}}{{ $release }}.{{end}}{{ $domain }}"
          volumeMounts:
            - name: kafka-truststore
              mountPath: "/opt/kafka/certificates"
              readOnly: true
          envFrom:
            - secretRef:
                name: keycloak-secrets
            - secretRef:
                name: ches
            - configMapRef:
                name: mail-settings
            - secretRef:
                name: jum-kafka-config-notification
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: kafka-truststore
          secret:
            secretName: kafka-cluster-client-truststore
        - name: truststore-key
          secret:
            secretName: kafka-cluster-client-key